### ISSUE TITLE
Not working in Firefox

### ISSUE THREAD

**Issue by jonathanlloyd** [coders-for-labour/lpgd-design-tool#20]
Tested in firefox `69.0.1` on Ubuntu

The pages doesn't load and I get the following error:
```
SyntaxError: invalid regexp group
```

Works in Chrome.

**Comment by TomFromThePool** [comment]
Probably related to the Safari issue which didn't like lookbehinds - will take a peek

**Comment by TomFromThePool** [comment]
Resolved and published
